# Generated by Django 4.2.3 on 2023-08-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upload_at', models.DateTimeField(auto_now=True)),
                ('seller_contact_number', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
